### ISSUE TITLE
Using a Service Principal instead of AZ CLI. Creating a value is never ending

### ISSUE THREAD

**Issue by Mimetis** [arkiaconsulting/terraform-provider-akc#4]
I still have a lot of issues, regarding the rights, when using a service principal
The value is indefinitely in the state of creating.

Here is my main.tf file

```
terraform {
  required_providers {
    akc = {
      source = "arkiaconsulting/akc"
    }
  }
}

provider "azurerm" {
  version = "=2.27.0"
  features {}
}


provider "null" {
  version = "~> 2.1"
}

provider "akc" {
}

# ---------------------------------------------------------

variable rg_prefix {
  default     = "rg-app-conf6"
}
variable rg_location {
  default     = "northeurope"
}
variable environment {
  default     = "dev"
}

# ---------------------------------------------------------
resource "random_string" "unique" {
  length  = 4
  special = false
  upper   = false
  number  = false
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.rg_prefix}-${var.environment}"
  location = var.rg_location
  tags = {
    environment = var.environment
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_app_configuration" "app_conf"{
  name                = "conf${var.environment}${random_string.unique.result}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "standard"

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

# Waiting for the assignment propagation
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }

  depends_on = [
    azurerm_app_configuration.app_conf
  ]
}

resource "akc_key_value" "rg_name" {
  endpoint = azurerm_app_configuration.app_conf.endpoint
  key      = "rg_name"
  value    = azurerm_resource_group.rg.name

  depends_on = [
    null_resource.delay
  ]

}

```

Here is my bash commands:

```
# Checking the SPN Role assignments before logout 
az role assignment list --assignee 88ef9e7c-XXX -o table

#Summary of the output 
 - App Configuration Data Owner  
 - Owner                         
 - Contributor

# Be sure I'm logout
az logout

# Exporting values as mentioned here : https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform

export ARM_CLIENT_ID=88ef9e7c-XXX
export ARM_SUBSCRIPTION_ID=6d854ccd-XXX
export ARM_TENANT_ID=72f988bf-XXX
export ARM_CLIENT_SECRET=W-tbXXX

# applying terraform script
terraform apply 

random_string.unique: Creating...
random_string.unique: Creation complete after 0s [id=fimx]
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 2s 
azurerm_app_configuration.app_conf: Creating...
azurerm_app_configuration.app_conf: Still creating... [10s elapsed]
azurerm_app_configuration.app_conf: Creation complete after 14s 
null_resource.delay: Creating...
null_resource.delay: Provisioning with 'local-exec'...
null_resource.delay (local-exec): Executing: ["/bin/sh" "-c" "sleep 60"]
null_resource.delay: Still creating... [10s elapsed]
null_resource.delay: Still creating... [20s elapsed]
null_resource.delay: Still creating... [30s elapsed]
null_resource.delay: Still creating... [40s elapsed]
null_resource.delay: Still creating... [50s elapsed]
null_resource.delay: Still creating... [1m0s elapsed]
null_resource.delay: Creation complete after 1m0s [id=4717629224581084020]
akc_key_value.rg_name: Creating...
akc_key_value.rg_name: Still creating... [10s elapsed]
akc_key_value.rg_name: Still creating... [20s elapsed]
akc_key_value.rg_name: Still creating... [30s elapsed]
akc_key_value.rg_name: Still creating... [40s elapsed]
akc_key_value.rg_name: Still creating... [50s elapsed]
akc_key_value.rg_name: Still creating... [1m0s elapsed]
akc_key_value.rg_name: Still creating... [1m10s elapsed]
akc_key_value.rg_name: Still creating... [1m20s elapsed]
akc_key_value.rg_name: Still creating... [1m30s elapsed]
akc_key_value.rg_name: Still creating... [1m40s elapsed]
akc_key_value.rg_name: Still creating... [1m50s elapsed]
akc_key_value.rg_name: Still creating... [2m0s elapsed]
akc_key_value.rg_name: Still creating... [2m10s elapsed]
akc_key_value.rg_name: Still creating... [2m20s elapsed]

```
Still waiting after 4 min :)

Once I interrupted the process, the error raised is:

```
**Error**: Unexpected error (): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://confdevqlzm.azconfig.io/kv/rg_name?api-version=1.0&label=%00: 
**StatusCode**=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fconfdevqlzm.azconfig.io": dial tcp 169.254.169.254:80: i/o timeout'
```

**Comment by arkiaconsulting** [comment]
Is the key-value effectively created in the App Configuration ?

Louis GERARD - Arkia Consulting
Microsoft Azure / .NET Developer / Industrialisation
+33 7 60 18 70 14
https://www.linkedin.com/in/louis-gérard-81988059/
________________________________
De : Sébastien Pertus <notifications@github.com>
Envoyé : Tuesday, October 6, 2020 4:52:34 PM
À : arkiaconsulting/terraform-provider-akc <terraform-provider-akc@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [arkiaconsulting/terraform-provider-akc] Using a Service Principal instead of AZ CLI. Creating a value is never ending (#4)


I still have a lot of issues, regarding the rights, when using a service principal
The value is indefinitely in the state of creating.

Here is my main.tf file

terraform {
  required_providers {
    akc = {
      source = "arkiaconsulting/akc"
    }
  }
}

provider "azurerm" {
  version = "=2.27.0"
  features {}
}


provider "null" {
  version = "~> 2.1"
}

provider "akc" {
}

# ---------------------------------------------------------

variable rg_prefix {
  default     = "rg-app-conf6"
}
variable rg_location {
  default     = "northeurope"
}
variable environment {
  default     = "dev"
}

# ---------------------------------------------------------
resource "random_string" "unique" {
  length  = 4
  special = false
  upper   = false
  number  = false
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.rg_prefix}-${var.environment}"
  location = var.rg_location
  tags = {
    environment = var.environment
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_app_configuration" "app_conf"{
  name                = "conf${var.environment}${random_string.unique.result}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "standard"

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

# Waiting for the assignment propagation
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }

  depends_on = [
    azurerm_app_configuration.app_conf
  ]
}

resource "akc_key_value" "rg_name" {
  endpoint = azurerm_app_configuration.app_conf.endpoint
  key      = "rg_name"
  value    = azurerm_resource_group.rg.name

  depends_on = [
    null_resource.delay
  ]

}



Here is my bash commands:

# Checking the SPN Role assignments before logout
az role assignment list --assignee 88ef9e7c-XXX -o table

#Summary of the output
 - App Configuration Data Owner
 - Owner
 - Contributor

# Be sure I'm logout
az logout

# Exporting values as mentioned here : https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform

export ARM_CLIENT_ID=88ef9e7c-XXX
export ARM_SUBSCRIPTION_ID=6d854ccd-XXX
export ARM_TENANT_ID=72f988bf-XXX
export ARM_CLIENT_SECRET=W-tbXXX

# applying terraform script
terraform apply

random_string.unique: Creating...
random_string.unique: Creation complete after 0s [id=fimx]
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 2s
azurerm_app_configuration.app_conf: Creating...
azurerm_app_configuration.app_conf: Still creating... [10s elapsed]
azurerm_app_configuration.app_conf: Creation complete after 14s
null_resource.delay: Creating...
null_resource.delay: Provisioning with 'local-exec'...
null_resource.delay (local-exec): Executing: ["/bin/sh" "-c" "sleep 60"]
null_resource.delay: Still creating... [10s elapsed]
null_resource.delay: Still creating... [20s elapsed]
null_resource.delay: Still creating... [30s elapsed]
null_resource.delay: Still creating... [40s elapsed]
null_resource.delay: Still creating... [50s elapsed]
null_resource.delay: Still creating... [1m0s elapsed]
null_resource.delay: Creation complete after 1m0s [id=4717629224581084020]
akc_key_value.rg_name: Creating...
akc_key_value.rg_name: Still creating... [10s elapsed]
akc_key_value.rg_name: Still creating... [20s elapsed]
akc_key_value.rg_name: Still creating... [30s elapsed]
akc_key_value.rg_name: Still creating... [40s elapsed]
akc_key_value.rg_name: Still creating... [50s elapsed]
akc_key_value.rg_name: Still creating... [1m0s elapsed]
akc_key_value.rg_name: Still creating... [1m10s elapsed]
akc_key_value.rg_name: Still creating... [1m20s elapsed]
akc_key_value.rg_name: Still creating... [1m30s elapsed]
akc_key_value.rg_name: Still creating... [1m40s elapsed]
akc_key_value.rg_name: Still creating... [1m50s elapsed]
akc_key_value.rg_name: Still creating... [2m0s elapsed]
akc_key_value.rg_name: Still creating... [2m10s elapsed]
akc_key_value.rg_name: Still creating... [2m20s elapsed]



Still waiting after 4 min :)

**Comment by arkiaman** [comment]
Is the key-value effectively created in the App Configuration ?

**Comment by Mimetis** [comment]
nop

**Comment by arkiaman** [comment]
By default, the credentials are fetched from the MSI endpoint (CLI), and fall back to environment credentials if it fails. I suspect that the call to the MSI endpoint has a way too long timeout.

I'll check if the timeout can be supplied.

**Comment by arkiaman** [comment]
As a workaround you can login first to the Azure CLI as a service principal

**Comment by Mimetis** [comment]
I know :)
Indeed with a service principal used for login it's working normally.

**Comment by arkiaman** [comment]
The reason why it's not working, is that you have configured the environment variables that are specific to the azurerm terraform provider.
Could you try by exporting your variables as:

```sh
export AZURE_CLIENT_ID=88ef9e7c-XXX
export AZURE_SUBSCRIPTION_ID=6d854ccd-XXX
export AZURE_TENANT_ID=72f988bf-XXX
export AZURE_CLIENT_SECRET=W-tbXXX
```

Reference [here](https://github.com/Azure/go-autorest/blob/ed56980f66527f60706fc564f6ac72723dcd61cf/autorest/azure/auth/auth.go#L37)

**Comment by Mimetis** [comment]
Got it thanks.
So far, the issue could be closed, since it's related on how are handled env var by the azurerm terraform provider

**Comment by arkiaman** [comment]
a43092afb43031f88b4ad5c1b1ed85ce5fe62337
